/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.doctorgateway.client.consultation.api;

import com.bytatech.ayoos.doctorgateway.client.consultation.model.BasicCheckUpDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-02-19T11:36:48.535+05:30[Asia/Calcutta]")

@Api(value = "BasicCheckUpResource", description = "the BasicCheckUpResource API")
public interface BasicCheckUpResourceApi {

    @ApiOperation(value = "createBasicCheckUp", nickname = "createBasicCheckUpUsingPOST", notes = "", response = BasicCheckUpDTO.class, tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BasicCheckUpDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/basic-check-ups",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<BasicCheckUpDTO> createBasicCheckUpUsingPOST(@ApiParam(value = "basicCheckUpDTO" ,required=true )  @Valid @RequestBody BasicCheckUpDTO basicCheckUpDTO);


    @ApiOperation(value = "deleteBasicCheckUp", nickname = "deleteBasicCheckUpUsingDELETE", notes = "", tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/basic-check-ups/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteBasicCheckUpUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllBasicCheckUps", nickname = "getAllBasicCheckUpsUsingGET", notes = "", response = BasicCheckUpDTO.class, responseContainer = "List", tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BasicCheckUpDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/basic-check-ups",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<BasicCheckUpDTO>> getAllBasicCheckUpsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getBasicCheckUp", nickname = "getBasicCheckUpUsingGET", notes = "", response = BasicCheckUpDTO.class, tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BasicCheckUpDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/basic-check-ups/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<BasicCheckUpDTO> getBasicCheckUpUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchBasicCheckUps", nickname = "searchBasicCheckUpsUsingGET", notes = "", response = BasicCheckUpDTO.class, responseContainer = "List", tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BasicCheckUpDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/basic-check-ups",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<BasicCheckUpDTO>> searchBasicCheckUpsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateBasicCheckUp", nickname = "updateBasicCheckUpUsingPUT", notes = "", response = BasicCheckUpDTO.class, tags={ "basic-check-up-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BasicCheckUpDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/basic-check-ups",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<BasicCheckUpDTO> updateBasicCheckUpUsingPUT(@ApiParam(value = "basicCheckUpDTO" ,required=true )  @Valid @RequestBody BasicCheckUpDTO basicCheckUpDTO);

}
